//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsProject005.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewsDBEntities1 : DbContext
    {
        public NewsDBEntities1()
            : base("name=NewsDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAuthority> tblAuthority { get; set; }
        public virtual DbSet<tblCategorys> tblCategorys { get; set; }
        public virtual DbSet<tblComments> tblComments { get; set; }
        public virtual DbSet<tblMedia> tblMedia { get; set; }
        public virtual DbSet<tblNews> tblNews { get; set; }
        public virtual DbSet<tblNewsCategoryMap> tblNewsCategoryMap { get; set; }
        public virtual DbSet<tblUsers> tblUsers { get; set; }
        public virtual DbSet<tblUsersAuthority> tblUsersAuthority { get; set; }
    }
}
