//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsProject005.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComments
    {
        public int YorumId { get; set; }
        public string YorumIcerik { get; set; }
        public int UyeId { get; set; }
        public int HaberId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual tblNews tblNews { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
