//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsProject005.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategorys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCategorys()
        {
            this.tblNewsCategoryMap = new HashSet<tblNewsCategoryMap>();
        }
    
        public int id { get; set; }
        public string categoryName { get; set; }
        public byte lockCategory { get; set; }
        public byte status { get; set; }
        public System.DateTime createdDate { get; set; }
        public System.DateTime editingDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNewsCategoryMap> tblNewsCategoryMap { get; set; }
    }
}
