//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsProject005.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNews
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNews()
        {
            this.tblComments = new HashSet<tblComments>();
            this.tblMedia = new HashSet<tblMedia>();
            this.tblNewsCategoryMap = new HashSet<tblNewsCategoryMap>();
        }
    
        public int Id { get; set; }
        public string newsSmallTitle { get; set; }
        public string newsTitle { get; set; }
        public string newsSummary { get; set; }
        public string newsDetail { get; set; }
        public int newsViewing { get; set; }
        public int newsTypeId { get; set; }
        public int newsUserAddId { get; set; }
        public int newsCuff { get; set; }
        public byte newsStatus { get; set; }
        public int newsConfirmation { get; set; }
        public System.DateTime createdDate { get; set; }
        public System.DateTime editingDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblComments> tblComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMedia> tblMedia { get; set; }
        public virtual tblUsers tblUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNewsCategoryMap> tblNewsCategoryMap { get; set; }
    }
}
