//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsProject005.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNewsCategoryMap
    {
        public int Id { get; set; }
        public int haber_id { get; set; }
        public int kategori_id { get; set; }
    
        public virtual tblCategorys tblCategorys { get; set; }
        public virtual tblNews tblNews { get; set; }
    }
}
