//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsProject005.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUsers()
        {
            this.tblComments = new HashSet<tblComments>();
            this.tblNews = new HashSet<tblNews>();
            this.tblUsersAuthority = new HashSet<tblUsersAuthority>();
        }
    
        public int Id { get; set; }
        public string images { get; set; }
        public string nameSurname { get; set; }
        public string mail { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public int authorityId { get; set; }
        public string facebook { get; set; }
        public string instagram { get; set; }
        public string twitter { get; set; }
        public string linkedin { get; set; }
        public System.DateTime editingDate { get; set; }
        public System.DateTime createdDate { get; set; }
    
        public virtual tblAuthority tblAuthority { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblComments> tblComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNews> tblNews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUsersAuthority> tblUsersAuthority { get; set; }
    }
}
